# Generated by Django 5.1.3 on 2025-01-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Talaba ismi')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email manzili')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqti')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Kursi')),
            ],
            options={
                'verbose_name': 'talaba ',
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
